package com.serdroid.hbm.model;
// Generated Dec 16, 2016 11:07:43 PM by Hibernate Tools 5.2.0.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Categories generated by hbm2java
 */
@Entity
@Table(name="categories"
    ,schema="public"
)
public class Categories  implements java.io.Serializable {


     private int category;
     private String categoryname;

    public Categories() {
    }

    public Categories(int category, String categoryname) {
       this.category = category;
       this.categoryname = categoryname;
    }
   
     @Id 

    
    @Column(name="category", unique=true, nullable=false)
    public int getCategory() {
        return this.category;
    }
    
    public void setCategory(int category) {
        this.category = category;
    }

    
    @Column(name="categoryname", nullable=false, length=50)
    public String getCategoryname() {
        return this.categoryname;
    }
    
    public void setCategoryname(String categoryname) {
        this.categoryname = categoryname;
    }




}


