package com.serdroid.hbm.model;
// Generated Dec 16, 2016 11:07:43 PM by Hibernate Tools 5.2.0.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Inventory generated by hbm2java
 */
@Entity
@Table(name="inventory"
    ,schema="public"
)
public class Inventory  implements java.io.Serializable {


     private int prodId;
     private int quanInStock;
     private int sales;

    public Inventory() {
    }

    public Inventory(int prodId, int quanInStock, int sales) {
       this.prodId = prodId;
       this.quanInStock = quanInStock;
       this.sales = sales;
    }
   
     @Id 

    
    @Column(name="prod_id", unique=true, nullable=false)
    public int getProdId() {
        return this.prodId;
    }
    
    public void setProdId(int prodId) {
        this.prodId = prodId;
    }

    
    @Column(name="quan_in_stock", nullable=false)
    public int getQuanInStock() {
        return this.quanInStock;
    }
    
    public void setQuanInStock(int quanInStock) {
        this.quanInStock = quanInStock;
    }

    
    @Column(name="sales", nullable=false)
    public int getSales() {
        return this.sales;
    }
    
    public void setSales(int sales) {
        this.sales = sales;
    }




}


