package com.serdroid.hbm.model;
// Generated Dec 16, 2016 11:07:43 PM by Hibernate Tools 5.2.0.Final


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Orders generated by hbm2java
 */
@Entity
@Table(name="orders"
    ,schema="public"
)
public class Orders  implements java.io.Serializable {


     private int orderid;
     private Date orderdate;
     private Integer customerid;
     private BigDecimal netamount;
     private BigDecimal tax;
     private BigDecimal totalamount;

    public Orders() {
    }

	
    public Orders(int orderid, Date orderdate, BigDecimal netamount, BigDecimal tax, BigDecimal totalamount) {
        this.orderid = orderid;
        this.orderdate = orderdate;
        this.netamount = netamount;
        this.tax = tax;
        this.totalamount = totalamount;
    }
    public Orders(int orderid, Date orderdate, Integer customerid, BigDecimal netamount, BigDecimal tax, BigDecimal totalamount) {
       this.orderid = orderid;
       this.orderdate = orderdate;
       this.customerid = customerid;
       this.netamount = netamount;
       this.tax = tax;
       this.totalamount = totalamount;
    }
   
     @Id 

    
    @Column(name="orderid", unique=true, nullable=false)
    public int getOrderid() {
        return this.orderid;
    }
    
    public void setOrderid(int orderid) {
        this.orderid = orderid;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="orderdate", nullable=false, length=13)
    public Date getOrderdate() {
        return this.orderdate;
    }
    
    public void setOrderdate(Date orderdate) {
        this.orderdate = orderdate;
    }

    
    @Column(name="customerid")
    public Integer getCustomerid() {
        return this.customerid;
    }
    
    public void setCustomerid(Integer customerid) {
        this.customerid = customerid;
    }

    
    @Column(name="netamount", nullable=false, precision=12)
    public BigDecimal getNetamount() {
        return this.netamount;
    }
    
    public void setNetamount(BigDecimal netamount) {
        this.netamount = netamount;
    }

    
    @Column(name="tax", nullable=false, precision=12)
    public BigDecimal getTax() {
        return this.tax;
    }
    
    public void setTax(BigDecimal tax) {
        this.tax = tax;
    }

    
    @Column(name="totalamount", nullable=false, precision=12)
    public BigDecimal getTotalamount() {
        return this.totalamount;
    }
    
    public void setTotalamount(BigDecimal totalamount) {
        this.totalamount = totalamount;
    }




}


