package com.serdroid.hbm.model;
// Generated Dec 16, 2016 11:07:43 PM by Hibernate Tools 5.2.0.Final


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Products generated by hbm2java
 */
@Entity
@Table(name="products"
    ,schema="public"
)
public class Products  implements java.io.Serializable {


     private int prodId;
     private int category;
     private String title;
     private String actor;
     private BigDecimal price;
     private Short special;
     private int commonProdId;

    public Products() {
    }

	
    public Products(int prodId, int category, String title, String actor, BigDecimal price, int commonProdId) {
        this.prodId = prodId;
        this.category = category;
        this.title = title;
        this.actor = actor;
        this.price = price;
        this.commonProdId = commonProdId;
    }
    public Products(int prodId, int category, String title, String actor, BigDecimal price, Short special, int commonProdId) {
       this.prodId = prodId;
       this.category = category;
       this.title = title;
       this.actor = actor;
       this.price = price;
       this.special = special;
       this.commonProdId = commonProdId;
    }
   
     @Id 

    
    @Column(name="prod_id", unique=true, nullable=false)
    public int getProdId() {
        return this.prodId;
    }
    
    public void setProdId(int prodId) {
        this.prodId = prodId;
    }

    
    @Column(name="category", nullable=false)
    public int getCategory() {
        return this.category;
    }
    
    public void setCategory(int category) {
        this.category = category;
    }

    
    @Column(name="title", nullable=false, length=50)
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }

    
    @Column(name="actor", nullable=false, length=50)
    public String getActor() {
        return this.actor;
    }
    
    public void setActor(String actor) {
        this.actor = actor;
    }

    
    @Column(name="price", nullable=false, precision=12)
    public BigDecimal getPrice() {
        return this.price;
    }
    
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    
    @Column(name="special")
    public Short getSpecial() {
        return this.special;
    }
    
    public void setSpecial(Short special) {
        this.special = special;
    }

    
    @Column(name="common_prod_id", nullable=false)
    public int getCommonProdId() {
        return this.commonProdId;
    }
    
    public void setCommonProdId(int commonProdId) {
        this.commonProdId = commonProdId;
    }




}


